name: Automated API tests using Postman CLI

# Trigger the workflow on push to the 'main' branch
on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4  # This checks out your repository
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "13569367-d9ade625-033f-497c-8bac-80e76ad3199b" -e "13569367-dee595b1-94f4-466f-8211-56e649f02454"